### ISSUE TITLE
Prioritize fixing formulae with livecheckables that currently error

### ISSUE THREAD

**Issue by samford** [Homebrew/homebrew-livecheck#363]
I've been working on updating existing livecheckables that produce an error, so that if we have to make changes to multiple formulae in the future, there's less work required to get CI to pass (since all modified formulae need to not error when livechecked). If you're looking to work on livecheckables and don't have any specific formulae in mind, it would be good to prioritize these first.

* [x] **aubio**: execution expired (#398)
* [x] **cling**: Unable to get versions (#394)
* [x] **entr**: Unable to get versions (#393)
* [x] **gcc**: Unable to get versions (#396)
* [x] **gdb**: Unable to get versions (#395)
* [x] **gwenhywfar**: Unable to get versions (#360)
* [x] **htpdate**: 404 Not Found (#361)
* [x] **ibex**: Unable to get versions (#362)
* [x] **imageoptim-cli**: Unable to get versions (#364)
* [x] **influxdb**: Unable to get versions (#392)
* [x] **jbig2dec**: 404 Not Found  (#391) 
* [x] **john-jumbo**: Unable to get versions (#390) 
* [x] **jython**: 404 Not Found (#389) 
* [x] **kapacitor**: Unable to get versions (#388) 
* [x] **kitchen-sync**: Unable to get versions (#387) 
* [x] **latex2html**: 404 Not Found (#386) 
* [x] **libnice**: 404 Not Found (#385) 
* [x] **librdkafka**: Unable to get versions (#384)
* [x] **libu2f-server**: redirection forbidden: https://developers.yubico.com/libu2f-server/Releases -> http://developers.yubico.com/libu2f-server/Releases/ (#383)
* [x] **libupnp**: Unable to get versions (#382)
* [x] **mkvtoolnix**: Unable to get versions (#414, #397)
* [x] **mupdf-tools**: Unable to get versions (#381)
* [x] **netdata**: Unable to get versions (#380)
* [x] **opencv@2**: Unable to get versions (#379)
* [x] **percona-xtrabackup**: 403 Forbidden (#378)
* [x] **pjproject**: Unable to get versions (#377)
* [x] **povray**: Unable to get versions (#376)
* [x] **rabbitmq**: 404 Not Found (#375)
* [x] **rakudo-star**: Unable to get versions (#374)
* [x] **scamper**: Unable to get versions (#373)
* [x] **sound-touch**: Unable to get versions (#372)
* [x] **speech-tools**: Failed to open TCP connection to festvox.org:80 (getaddrinfo: nodename nor servname provided, or not known) (#371)
* [x] **sshfs**: Unable to get versions (#370)
* [x] **suite-sparse**: Unable to get versions (#369)
* [x] **telegraf**: Unable to get versions (#368)
* [x] **verilator**: Unable to get versions (#367)
* [x] **vips**: Unable to get versions (#365)
* [x] **wiredtiger**: Unable to get versions (#366)
* [x] **zookeeper**: Unable to get versions (#317)

**Comment by samford** [comment]
To anyone who sees this, please hold off on merging Rui's PRs. I've been reviewing them to make sure that he's going in the right direction and to provide feedback on how to improve the commit. Once the commit's in good shape, I finally merge them.

It's a time-consuming process but it's only temporary, while he becomes familiar with what we want in a livecheckable (as well as what we want to avoid in a livecheckable). The end goal is that this instruction will lead to quality commits without all the review and feedback (at least for straightforward livecheckable contributions).

In the future, I hope to codify all these tips and norms into documentation (to greatly reduce this work when someone starts contributing to livecheck) but I don't have the time to write it all down just yet. I'm working on it little by little, as time permits.

**Comment by chenrui333** [comment]
I also request you as PR reviewer as open PRs, so it is more visible :)

**Comment by samford** [comment]
Now that these issues have all been addressed, the only formulae with errors at present are:

* **acpica**: Error: acpica: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (self signed certificate in certificate chain)
* **speech-tools**: Error: speech-tools: Failed to open TCP connection to festvox.org:80 (getaddrinfo: nodename nor servname provided, or not known)

The `acpica` issue is due to their website's SSL certificate being messed up, so it's out of our hands. The CAPTCHA's broken on their contact form, so I can't even send them a message to let them know 😞 

The `speech-tools` issue is intermittent. It recently failed on a livecheck run but I just ran it again and it was fine. The upstream server must be unreliable, which we also can't fix.

Overall, this is an improvement over where we started. These were the livecheckables that were left after I started working on fixing errors for formulae with existing livecheckables and Rui helped to finish this off (not to mention Eric's apache.org PR). Thanks to everyone involved!
